Add video
clover-coop/green_city_app pull request #2
Opened 2023-04-05 22:48 UTC by VeeTsien

- add youtube player service 
- update routes transition animation 
- update android settings for successful build
- make the home logo clickable to navigate home

2023-04-05 23:15 UTC, lukemadera commented on frontend/lib/app_scaffold.dart
> +  Widget _buildUserButton(BuildContext context, currentUserState,
Curious about these style changes - are you doing this manually or is this auto formatting?

2023-04-05 23:16 UTC, lukemadera commented on frontend/lib/app_scaffold.dart
> +  Widget _buildUserButton(BuildContext context, currentUserState,
If we want to change styling it would be nice to align on them and then have a PR to do them all to make PR reviews / git diffs easier.

2023-04-05 23:16 UTC, lukemadera commented on frontend/lib/app_scaffold.dart
> +          onTap: () => context.go(Routes.home),
Is this the only actual change in this file? Can we revert the rest?

2023-04-05 23:17 UTC, lukemadera commented on frontend/lib/modules/design.dart
> +import 'package:green_city_app/common/youtube_service.dart';
Can we use relative imports?

2023-04-05 23:18 UTC, lukemadera commented on frontend/lib/routes.dart
> +                  return FadeTransition(
Oh wow, is there not a setting to apply a default to all of them? If it requires this much extra code, maybe it's not worth it!

2023-04-05 23:19 UTC, lukemadera requested changes
Youtube changes look good! Seems there is a lot of extra code diffs though; let's chat through that?

2023-04-05 23:54 UTC, VeeTsien commented on frontend/lib/modules/design.dart
> +import 'package:green_city_app/common/youtube_service.dart';
Yep, I will update it!

2023-04-06 00:19 UTC, VeeTsien commented
Closing cause it's included in a better pr https://github.com/clover-coop/green_city_app/pull/4

2023-04-06 00:19 UTC, closed without merging